INFO:root:Path processing /pictures/png/1
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/1.png
INFO:root:Path processing /no.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.css') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/no.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/no.css
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/no.css
INFO:root:Path processing /mime/
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/1.png
INFO:root:Path processing /index.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Path processing /1.2.3.txt
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/1.2.3.txt
INFO:root:Path processing /foo.bar
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/foo.bar
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/foo.bar
INFO:root:Path processing /any.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/any.html
INFO:root:Path processing /2.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/2.html
INFO:root:Path processing /123.css
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/123.css
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Path processing /new page.html
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.html') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/new page.html
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/new page.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/new page.html
INFO:root:Parsing request by file started
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Parsing request by file started
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:server is UP on 0.0.0.0:8000
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:server is UP on 0.0.0.0:8000
ERROR:root:server is DOWN because of exception <class 'TypeError'> _accept() takes 2 positional arguments but 3 were given <traceback object at 0x10c36ccd0>
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/tests/test_server.py", line 114, in test_serving
    s.serve()
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 76, in serve
    callback(key.fileobj, mask)
TypeError: _accept() takes 2 positional arguments but 3 were given
INFO:root:Path processing /pictures/png/1
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/1.png
INFO:root:Path processing /no.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.css') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/no.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/no.css
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/no.css
INFO:root:Path processing /mime/
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/1.png
INFO:root:Path processing /index.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Path processing /1.2.3.txt
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/1.2.3.txt
INFO:root:Path processing /foo.bar
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/foo.bar
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/foo.bar
INFO:root:Path processing /any.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/any.html
INFO:root:Path processing /2.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/2.html
INFO:root:Path processing /123.css
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/123.css
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Path processing /new page.html
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.html') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/new page.html
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/new page.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/new page.html
INFO:root:Parsing request by file started
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Parsing request by file started
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:server is UP on 0.0.0.0:8000
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Connected ('127.0.0.1', 53711)
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Threaded client serving started ('127.0.0.1', 53711) in thread 4438060480
INFO:root:Request parsed from ('127.0.0.1', 53711) method: GET
target: /
version: HTTP/1.1
headers: Host: 0.0.0.0
Accept: */*


file: <_io.BytesIO object at 0x101adaef0>
user: ('127.0.0.1', 53711)
url: ParseResult(scheme='', netloc='', path='/', params='', query='', fragment='')
path: /
query: {}
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/html'), ('Content-Disposition', 'inline; filename=index.html'), ('Content-Length', 156)]
body: b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>index.html</title>\n</head>\n<body>\n    <h1>Python Rule it!</h1>\n</body>\n</html>'
INFO:root:271B sent to ('127.0.0.1', 53711)
INFO:root:Files sent to ('127.0.0.1', 53711)
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/html'), ('Content-Disposition', 'inline; filename=index.html'), ('Content-Length', 156)]
body: b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>index.html</title>\n</head>\n<body>\n    <h1>Python Rule it!</h1>\n</body>\n</html>'
ERROR:root:No data received
ERROR:root:Client handling failed (123145455173632) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Threaded client serving started ('127.0.0.1', 53711) in thread 4438060480
INFO:root:107B sent to ('127.0.0.1', 53711)
ERROR:root:No data received
INFO:root:Socket in thread 4438060480 was disconnected [Errno 22] Invalid argument
INFO:root:Files sent to ('127.0.0.1', 53711)
ERROR:root:Client handling failed (123145460428800) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Socket Disconnected in thread 4438060480
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Connected ('127.0.0.1', 53712)
INFO:root:Request parsing by connection started
INFO:root:Threaded client serving started ('127.0.0.1', 53712) in thread 4669779392
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53712) method: GET
target: /server.log
version: HTTP/1.1
headers: Host: 0.0.0.0:8000
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive


file: <_io.BytesIO object at 0x1100b0fb0>
user: ('127.0.0.1', 53712)
url: ParseResult(scheme='', netloc='', path='/server.log', params='', query='', fragment='')
path: /server.log
query: {}
INFO:root:Path processing /server.log
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/server.log
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/server.log
ERROR:root:No data received
ERROR:root:Client handling failed (123145430982656) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/plain'), ('Content-Disposition', 'inline; filename=server.log'), ('Content-Length', 65220561)]
body: b'INFO:root:server is UP on 0.0.0.0:8000\nINFO:root:Connected (\'127.0.0.1\', 50810)\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasda
INFO:root:Threaded client serving started ('127.0.0.1', 53712) in thread 4669779392
INFO:root:107B sent to ('127.0.0.1', 53712)
INFO:root:Connected ('127.0.0.1', 53713)
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/plain'), ('Content-Disposition', 'inline; filename=server.log'), ('Content-Length', 65220561)]
body: b'INFO:root:server is UP on 0.0.0.0:8000\nINFO:root:Connected (\'127.0.0.1\', 50810)\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasda
INFO:root:Files sent to ('127.0.0.1', 53712)
INFO:root:Socket in thread 4669779392 was disconnected [Errno 22] Invalid argument
ERROR:root:No data received
INFO:root:Socket Disconnected in thread 4669779392
ERROR:root:Client handling failed (123145436237824) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
ERROR:root:Connection with client broken
INFO:root:Threaded client serving started ('127.0.0.1', 53713) in thread 4669779392
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53713) method: GET
target: /server.log
version: HTTP/1.1
headers: Host: 0.0.0.0:8000
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive


file: <_io.BytesIO object at 0x110144170>
user: ('127.0.0.1', 53713)
url: ParseResult(scheme='', netloc='', path='/server.log', params='', query='', fragment='')
path: /server.log
query: {}
INFO:root:Path processing /server.log
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/server.log
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/server.log
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/plain'), ('Content-Disposition', 'inline; filename=server.log'), ('Content-Length', 65220561)]
body: b'INFO:root:server is UP on 0.0.0.0:8000\nINFO:root:Connected (\'127.0.0.1\', 50810)\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasda
INFO:root:817120B sent to ('127.0.0.1', 53713)
INFO:root:1193016B sent to ('127.0.0.1', 53713)
INFO:root:899144B sent to ('127.0.0.1', 53713)
INFO:root:883280B sent to ('127.0.0.1', 53713)
INFO:root:1087924B sent to ('127.0.0.1', 53713)
INFO:root:916048B sent to ('127.0.0.1', 53713)
INFO:root:1145840B sent to ('127.0.0.1', 53713)
INFO:root:1064024B sent to ('127.0.0.1', 53713)
INFO:root:1129560B sent to ('127.0.0.1', 53713)
INFO:root:826508B sent to ('127.0.0.1', 53713)
INFO:root:1064024B sent to ('127.0.0.1', 53713)
INFO:root:1063608B sent to ('127.0.0.1', 53713)
INFO:root:1128728B sent to ('127.0.0.1', 53713)
INFO:root:998072B sent to ('127.0.0.1', 53713)
INFO:root:1064024B sent to ('127.0.0.1', 53713)
INFO:root:867416B sent to ('127.0.0.1', 53713)
INFO:root:998072B sent to ('127.0.0.1', 53713)
INFO:root:1128728B sent to ('127.0.0.1', 53713)
INFO:root:932952B sent to ('127.0.0.1', 53713)
INFO:root:932952B sent to ('127.0.0.1', 53713)
INFO:root:1194056B sent to ('127.0.0.1', 53713)
INFO:root:867416B sent to ('127.0.0.1', 53713)
INFO:root:1064024B sent to ('127.0.0.1', 53713)
INFO:root:1128728B sent to ('127.0.0.1', 53713)
INFO:root:932952B sent to ('127.0.0.1', 53713)
INFO:root:932952B sent to ('127.0.0.1', 53713)
INFO:root:1064024B sent to ('127.0.0.1', 53713)
INFO:root:998072B sent to ('127.0.0.1', 53713)
INFO:root:1064024B sent to ('127.0.0.1', 53713)
INFO:root:761388B sent to ('127.0.0.1', 53713)
INFO:root:859380B sent to ('127.0.0.1', 53713)
INFO:root:1128728B sent to ('127.0.0.1', 53713)
INFO:root:1079940B sent to ('127.0.0.1', 53713)
INFO:root:1129144B sent to ('127.0.0.1', 53713)
INFO:root:842060B sent to ('127.0.0.1', 53713)
INFO:root:1480932B sent to ('127.0.0.1', 53713)
INFO:root:1480932B sent to ('127.0.0.1', 53713)
INFO:root:1611588B sent to ('127.0.0.1', 53713)
INFO:root:2069508B sent to ('127.0.0.1', 53713)
INFO:root:1677124B sent to ('127.0.0.1', 53713)
INFO:root:1742244B sent to ('127.0.0.1', 53713)
INFO:root:1611588B sent to ('127.0.0.1', 53713)
INFO:root:1612004B sent to ('127.0.0.1', 53713)
INFO:root:1611588B sent to ('127.0.0.1', 53713)
INFO:root:1743076B sent to ('127.0.0.1', 53713)
INFO:root:1872900B sent to ('127.0.0.1', 53713)
INFO:root:1546884B sent to ('127.0.0.1', 53713)
INFO:root:1546468B sent to ('127.0.0.1', 53713)
INFO:root:1743076B sent to ('127.0.0.1', 53713)
INFO:root:1546884B sent to ('127.0.0.1', 53713)
INFO:root:2520016B sent to ('127.0.0.1', 53713)
INFO:root:1488344B sent to ('127.0.0.1', 53713)
INFO:root:965720B sent to ('127.0.0.1', 53713)
INFO:root:161878B sent to ('127.0.0.1', 53713)
INFO:root:Files sent to ('127.0.0.1', 53713)
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/plain'), ('Content-Disposition', 'inline; filename=server.log'), ('Content-Length', 65220561)]
body: b'INFO:root:server is UP on 0.0.0.0:8000\nINFO:root:Connected (\'127.0.0.1\', 50810)\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasda
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53713) method: GET
target: /server.log
version: HTTP/1.1
headers: Host: 0.0.0.0:8000
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive


file: <_io.BytesIO object at 0x110144230>
user: ('127.0.0.1', 53713)
url: ParseResult(scheme='', netloc='', path='/server.log', params='', query='', fragment='')
path: /server.log
query: {}
INFO:root:Threaded client serving started ('127.0.0.1', 53713) in thread 4669779392
INFO:root:Path processing /server.log
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/server.log
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/server.log
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/plain'), ('Content-Disposition', 'inline; filename=server.log'), ('Content-Length', 65220561)]
body: b'INFO:root:server is UP on 0.0.0.0:8000\nINFO:root:Connected (\'127.0.0.1\', 50810)\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasda
INFO:root:1555128B sent to ('127.0.0.1', 53713)
INFO:root:1775844B sent to ('127.0.0.1', 53713)
INFO:root:1645188B sent to ('127.0.0.1', 53713)
INFO:root:1645188B sent to ('127.0.0.1', 53713)
INFO:root:1710308B sent to ('127.0.0.1', 53713)
INFO:root:1775844B sent to ('127.0.0.1', 53713)
INFO:root:1579236B sent to ('127.0.0.1', 53713)
INFO:root:2193168B sent to ('127.0.0.1', 53713)
INFO:root:1579236B sent to ('127.0.0.1', 53713)
INFO:root:1709892B sent to ('127.0.0.1', 53713)
INFO:root:1710308B sent to ('127.0.0.1', 53713)
INFO:root:1775844B sent to ('127.0.0.1', 53713)
INFO:root:1710308B sent to ('127.0.0.1', 53713)
INFO:root:1644772B sent to ('127.0.0.1', 53713)
INFO:root:1645188B sent to ('127.0.0.1', 53713)
INFO:root:1906500B sent to ('127.0.0.1', 53713)
INFO:root:1775428B sent to ('127.0.0.1', 53713)
INFO:root:2037572B sent to ('127.0.0.1', 53713)
INFO:root:1685368B sent to ('127.0.0.1', 53713)
INFO:root:1775428B sent to ('127.0.0.1', 53713)
INFO:root:1775844B sent to ('127.0.0.1', 53713)
INFO:root:1841380B sent to ('127.0.0.1', 53713)
INFO:root:1906500B sent to ('127.0.0.1', 53713)
INFO:root:1579652B sent to ('127.0.0.1', 53713)
INFO:root:1710724B sent to ('127.0.0.1', 53713)
INFO:root:1710308B sent to ('127.0.0.1', 53713)
INFO:root:1906084B sent to ('127.0.0.1', 53713)
INFO:root:1620248B sent to ('127.0.0.1', 53713)
INFO:root:1907332B sent to ('127.0.0.1', 53713)
INFO:root:2069924B sent to ('127.0.0.1', 53713)
INFO:root:2004804B sent to ('127.0.0.1', 53713)
INFO:root:1816440B sent to ('127.0.0.1', 53713)
INFO:root:1938852B sent to ('127.0.0.1', 53713)
INFO:root:1939268B sent to ('127.0.0.1', 53713)
INFO:root:2135044B sent to ('127.0.0.1', 53713)
INFO:root:1554296B sent to ('127.0.0.1', 53713)
INFO:root:968234B sent to ('127.0.0.1', 53713)
INFO:root:Files sent to ('127.0.0.1', 53713)
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/plain'), ('Content-Disposition', 'inline; filename=server.log'), ('Content-Length', 65220561)]
body: b'INFO:root:server is UP on 0.0.0.0:8000\nINFO:root:Connected (\'127.0.0.1\', 50810)\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasda
INFO:root:Connected ('127.0.0.1', 53717)
INFO:root:Threaded client serving started ('127.0.0.1', 53717) in thread 4669779392
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53717) method: GET
target: /server.log
version: HTTP/1.1
headers: Host: 0.0.0.0:8000
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive


file: <_io.BytesIO object at 0x110144170>
user: ('127.0.0.1', 53717)
url: ParseResult(scheme='', netloc='', path='/server.log', params='', query='', fragment='')
path: /server.log
query: {}
INFO:root:Path processing /server.log
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/server.log
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/server.log
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/plain'), ('Content-Disposition', 'inline; filename=server.log'), ('Content-Length', 65220561)]
body: b'INFO:root:server is UP on 0.0.0.0:8000\nINFO:root:Connected (\'127.0.0.1\', 50810)\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasda
INFO:root:981116B sent to ('127.0.0.1', 53717)
INFO:root:1063296B sent to ('127.0.0.1', 53717)
INFO:root:1587220B sent to ('127.0.0.1', 53717)
INFO:root:1587636B sent to ('127.0.0.1', 53717)
INFO:root:875400B sent to ('127.0.0.1', 53717)
INFO:root:1636372B sent to ('127.0.0.1', 53717)
INFO:root:1571096B sent to ('127.0.0.1', 53717)
INFO:root:1571460B sent to ('127.0.0.1', 53717)
INFO:root:1439192B sent to ('127.0.0.1', 53717)
INFO:root:1767236B sent to ('127.0.0.1', 53717)
INFO:root:1898308B sent to ('127.0.0.1', 53717)
INFO:root:1571460B sent to ('127.0.0.1', 53717)
INFO:root:1701700B sent to ('127.0.0.1', 53717)
INFO:root:2029328B sent to ('127.0.0.1', 53717)
INFO:root:1767652B sent to ('127.0.0.1', 53717)
INFO:root:1865904B sent to ('127.0.0.1', 53717)
INFO:root:2062564B sent to ('127.0.0.1', 53717)
INFO:root:1865956B sent to ('127.0.0.1', 53717)
INFO:root:1931492B sent to ('127.0.0.1', 53717)
INFO:root:1931492B sent to ('127.0.0.1', 53717)
INFO:root:2750640B sent to ('127.0.0.1', 53717)
INFO:root:1931076B sent to ('127.0.0.1', 53717)
INFO:root:1865124B sent to ('127.0.0.1', 53717)
INFO:root:1603812B sent to ('127.0.0.1', 53717)
INFO:root:1930660B sent to ('127.0.0.1', 53717)
INFO:root:1931076B sent to ('127.0.0.1', 53717)
INFO:root:1112760B sent to ('127.0.0.1', 53717)
INFO:root:1800004B sent to ('127.0.0.1', 53717)
INFO:root:1931492B sent to ('127.0.0.1', 53717)
INFO:root:1734884B sent to ('127.0.0.1', 53717)
INFO:root:2619152B sent to ('127.0.0.1', 53717)
INFO:root:1767704B sent to ('127.0.0.1', 53717)
INFO:root:1931076B sent to ('127.0.0.1', 53717)
INFO:root:1734884B sent to ('127.0.0.1', 53717)
INFO:root:2061316B sent to ('127.0.0.1', 53717)
INFO:root:1734468B sent to ('127.0.0.1', 53717)
INFO:root:1865540B sent to ('127.0.0.1', 53717)
ERROR:root:[Errno 35] Resource temporarily unavailable Sleeping 0.1s
INFO:root:209134B sent to ('127.0.0.1', 53717)
INFO:root:Files sent to ('127.0.0.1', 53717)
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/plain'), ('Content-Disposition', 'inline; filename=server.log'), ('Content-Length', 65220561)]
body: b'INFO:root:server is UP on 0.0.0.0:8000\nINFO:root:Connected (\'127.0.0.1\', 50810)\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasda
INFO:root:Threaded client serving started ('127.0.0.1', 53713) in thread 4669779392
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53713) method: GET
target: /page-load-errors.css
version: HTTP/1.1
headers: Host: 0.0.0.0:8000
Connection: keep-alive
Accept: text/css,*/*;q=0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Referer: http://0.0.0.0:8000/s
Accept-Encoding: gzip, deflate


file: <_io.BytesIO object at 0x110144230>
user: ('127.0.0.1', 53713)
url: ParseResult(scheme='', netloc='', path='/page-load-errors.css', params='', query='', fragment='')
path: /page-load-errors.css
query: {}
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53717) method: GET
target: /s
version: HTTP/1.1
headers: Host: 0.0.0.0:8000
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive


file: <_io.BytesIO object at 0x1100b0e90>
user: ('127.0.0.1', 53717)
url: ParseResult(scheme='', netloc='', path='/s', params='', query='', fragment='')
path: /s
query: {}
INFO:root:Threaded client serving started ('127.0.0.1', 53717) in thread 4669779392
INFO:root:Connected ('127.0.0.1', 53718)
INFO:root:Path processing /s
ERROR:root:Client handling failed (123145436237824) (404, 'Not found', '', 'PAGE_NOT_FOUND')
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 194, in handle_req
    destination = self.ruler.get_destination(path, rules, True)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/pathfinder.py", line 56, in get_destination
    raise FileNotFoundError(url, rules)
FileNotFoundError: [Errno /s] {'/': 'tmp/index.html', '/favicon.ico': 'tmp/pictures/favicon.ico', '/index.html': 'tmp/index.html', '/2.html': 'tmp/pages/2.html', '/1.2.3.txt': 'tmp/1.2.3.txt', '/page-load-errors[extras].css': {'path': 'pages/page-load-errors[extras].css', 'mime': 'text/css'}, '/[name].html': 'tmp/pages/[name].html', '/[name].css': 'tmp/pages/css/[name].css', '/[name].[ext]': 'tmp/pictures/[name].[ext]', '/png/[name].png': 'tmp/pictures/[name].png', '/pictures/[ext]/1': 'tmp/pictures/1.[ext]', '/[day]-[n]/[month]/[year]': 'tmp/dates/[year]/[month]/[day]/[n].png', '/[DD]/[MM]/[YY]': 'tmp/dates/[DD].[MM].[YY].png', '/mime/': {'path': 'tmp/pictures/1.png', 'mime': 'text/txt'}, '/big': {'path': 'tmp/pictures/chroma.jpg', 'mime': 'image/jpg'}, '/[file].[ext]': 'tmp/[file].[ext]'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 111, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 196, in handle_req
    raise Errors.NOT_FOUND
errors.Error: (404, 'Not found', '', 'PAGE_NOT_FOUND')
ERROR:root:No data received
INFO:root:Threaded client serving started ('127.0.0.1', 53717) in thread 4669779392
INFO:root:Path processing /page-load-errors.css
ERROR:root:Client handling failed (123145425727488) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Connected ('127.0.0.1', 53719)
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/pages/page-load-errors.css
INFO:root:107B sent to ('127.0.0.1', 53717)
INFO:root:Files sent to ('127.0.0.1', 53717)
INFO:root:Threaded client serving started ('127.0.0.1', 53718) in thread 4669779392
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
ERROR:root:No data received
INFO:root:Socket in thread 4669779392 was disconnected [Errno 22] Invalid argument
INFO:root:Request parsed
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/css'), ('Content-Disposition', 'inline; filename=page-load-errors.css'), ('Content-Length', 1129)]
body: b'/*\n    This file has a UTF-8 BOM in it so it can be included from a UTF-16 page\n    without specifying an explicit character set. When editing it, please be\n    sure to preserve the BOM (first three bytes of the file, EF BB BF).\n */\n\nbody {\n    background: rgb(246, 246, 246);\n    cursor: default;\n    display: -webkit-box;\n    text-align: center;\n    -webkit-box-align: center;\n    -webkit-box-pack: center;\n    -webkit-user-select: none;\n}\n\na {\n    color: rgb(21, 126, 251);\n   
ERROR:root:Client handling failed (123145425727488) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Socket Disconnected in thread 4669779392
INFO:root:Request parsed from ('127.0.0.1', 53718) method: GET
target: /page-load-errors-extras.css
version: HTTP/1.1
headers: Host: 0.0.0.0:8000
Connection: keep-alive
Accept: text/css,*/*;q=0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Referer: http://0.0.0.0:8000/s
Accept-Encoding: gzip, deflate


file: <_io.BytesIO object at 0x11014bcb0>
user: ('127.0.0.1', 53718)
url: ParseResult(scheme='', netloc='', path='/page-load-errors-extras.css', params='', query='', fragment='')
path: /page-load-errors-extras.css
query: {}
INFO:root:1254B sent to ('127.0.0.1', 53713)
INFO:root:Connected ('127.0.0.1', 53720)
INFO:root:Files sent to ('127.0.0.1', 53713)
INFO:root:Path processing /page-load-errors-extras.css
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/css'), ('Content-Disposition', 'inline; filename=page-load-errors.css'), ('Content-Length', 1129)]
body: b'/*\n    This file has a UTF-8 BOM in it so it can be included from a UTF-16 page\n    without specifying an explicit character set. When editing it, please be\n    sure to preserve the BOM (first three bytes of the file, EF BB BF).\n */\n\nbody {\n    background: rgb(246, 246, 246);\n    cursor: default;\n    display: -webkit-box;\n    text-align: center;\n    -webkit-box-align: center;\n    -webkit-box-pack: center;\n    -webkit-user-select: none;\n}\n\na {\n    color: rgb(21, 126, 251);\n   
INFO:root:Threaded client serving started ('127.0.0.1', 53719) in thread 4669779392
INFO:root:Request parsing by connection started
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/pages/page-load-errors-extras.css
INFO:root:Parsing request by file started
ERROR:root:No data received
INFO:root:Threaded client serving started ('127.0.0.1', 53719) in thread 4669779392
ERROR:root:Client handling failed (123145430982656) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Request parsed
INFO:root:Request parsing by connection started
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/css'), ('Content-Disposition', 'inline; filename=page-load-errors-extras.css'), ('Content-Length', 407)]
body: b'/*\n    This file has a UTF-8 BOM in it so it can be included from a UTF-16 page\n    without specifying an explicit character set. When editing it, please be\n    sure to preserve the BOM (first three bytes of the file, EF BB BF).\n*/\n\n@media (prefers-dark-interface) {\n    body {\n        background: rgb(30, 30, 30);\n    }\n\n    .error-message, .suggestion-prompt {\n        color: rgb(110, 110, 110);\n    }\n}\n\n'
INFO:root:Threaded client serving started ('127.0.0.1', 53720) in thread 4669779392
INFO:root:107B sent to ('127.0.0.1', 53719)
INFO:root:Request parsed from ('127.0.0.1', 53719) method: GET
target: /
version: HTTP/1.1
headers: Host: 0.0.0.0:8000
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive


file: <_io.BytesIO object at 0x11014bf50>
user: ('127.0.0.1', 53719)
url: ParseResult(scheme='', netloc='', path='/', params='', query='', fragment='')
path: /
query: {}
INFO:root:Parsing request by file started
INFO:root:538B sent to ('127.0.0.1', 53718)
INFO:root:Files sent to ('127.0.0.1', 53719)
ERROR:root:No data received
INFO:root:Socket in thread 4669779392 was disconnected [Errno 22] Invalid argument
INFO:root:Request parsed
INFO:root:Path processing /
INFO:root:Files sent to ('127.0.0.1', 53718)
ERROR:root:Client handling failed (123145446748160) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Socket Disconnected in thread 4669779392
INFO:root:Request parsed from ('127.0.0.1', 53720) method: GET
target: /
version: HTTP/1.1
headers: Host: 0.0.0.0:8000
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive


file: <_io.BytesIO object at 0x110154dd0>
user: ('127.0.0.1', 53720)
url: ParseResult(scheme='', netloc='', path='/', params='', query='', fragment='')
path: /
query: {}
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/css'), ('Content-Disposition', 'inline; filename=page-load-errors-extras.css'), ('Content-Length', 407)]
body: b'/*\n    This file has a UTF-8 BOM in it so it can be included from a UTF-16 page\n    without specifying an explicit character set. When editing it, please be\n    sure to preserve the BOM (first three bytes of the file, EF BB BF).\n*/\n\n@media (prefers-dark-interface) {\n    body {\n        background: rgb(30, 30, 30);\n    }\n\n    .error-message, .suggestion-prompt {\n        color: rgb(110, 110, 110);\n    }\n}\n\n'
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/html'), ('Content-Disposition', 'inline; filename=index.html'), ('Content-Length', 156)]
body: b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>index.html</title>\n</head>\n<body>\n    <h1>Python Rule it!</h1>\n</body>\n</html>'
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/html'), ('Content-Disposition', 'inline; filename=index.html'), ('Content-Length', 156)]
body: b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>index.html</title>\n</head>\n<body>\n    <h1>Python Rule it!</h1>\n</body>\n</html>'
ERROR:root:Connection with client broken
INFO:root:271B sent to ('127.0.0.1', 53720)
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/html'), ('Content-Disposition', 'inline; filename=index.html'), ('Content-Length', 156)]
body: b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>index.html</title>\n</head>\n<body>\n    <h1>Python Rule it!</h1>\n</body>\n</html>'
INFO:root:Files sent to ('127.0.0.1', 53720)
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/html'), ('Content-Disposition', 'inline; filename=index.html'), ('Content-Length', 156)]
body: b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>index.html</title>\n</head>\n<body>\n    <h1>Python Rule it!</h1>\n</body>\n</html>'
INFO:root:Connected ('127.0.0.1', 53721)
INFO:root:Threaded client serving started ('127.0.0.1', 53721) in thread 4669779392
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53721) method: GET
target: /server.log
version: HTTP/1.1
headers: Host: 0.0.0.0:8000
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive


file: <_io.BytesIO object at 0x11014bbf0>
user: ('127.0.0.1', 53721)
url: ParseResult(scheme='', netloc='', path='/server.log', params='', query='', fragment='')
path: /server.log
query: {}
INFO:root:Path processing /server.log
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/server.log
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/server.log
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/plain'), ('Content-Disposition', 'inline; filename=server.log'), ('Content-Length', 65220561)]
body: b'INFO:root:server is UP on 0.0.0.0:8000\nINFO:root:Connected (\'127.0.0.1\', 50810)\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasda
INFO:root:621240B sent to ('127.0.0.1', 53721)
INFO:root:981532B sent to ('127.0.0.1', 53721)
INFO:root:1096220B sent to ('127.0.0.1', 53721)
INFO:root:916048B sent to ('127.0.0.1', 53721)
INFO:root:915840B sent to ('127.0.0.1', 53721)
INFO:root:915840B sent to ('127.0.0.1', 53721)
INFO:root:932224B sent to ('127.0.0.1', 53721)
INFO:root:1284012B sent to ('127.0.0.1', 53721)
INFO:root:1431780B sent to ('127.0.0.1', 53721)
INFO:root:1514116B sent to ('127.0.0.1', 53721)
INFO:root:1521060B sent to ('127.0.0.1', 53721)
INFO:root:1587012B sent to ('127.0.0.1', 53721)
INFO:root:1227292B sent to ('127.0.0.1', 53721)
INFO:root:1390820B sent to ('127.0.0.1', 53721)
INFO:root:1325700B sent to ('127.0.0.1', 53721)
INFO:root:1357740B sent to ('127.0.0.1', 53721)
INFO:root:1718500B sent to ('127.0.0.1', 53721)
INFO:root:1227084B sent to ('127.0.0.1', 53721)
INFO:root:1570212B sent to ('127.0.0.1', 53721)
INFO:root:1260580B sent to ('127.0.0.1', 53721)
INFO:root:1439556B sent to ('127.0.0.1', 53721)
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53713) method: GET
target: /serve
version: HTTP/1.1
headers: Host: 0.0.0.0:8000
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive


file: <_io.BytesIO object at 0x11014bf50>
user: ('127.0.0.1', 53713)
url: ParseResult(scheme='', netloc='', path='/serve', params='', query='', fragment='')
path: /serve
query: {}
INFO:root:Threaded client serving started ('127.0.0.1', 53713) in thread 4669779392
INFO:root:1784452B sent to ('127.0.0.1', 53721)
INFO:root:Path processing /serve
ERROR:root:Client handling failed (123145430982656) (404, 'Not found', '', 'PAGE_NOT_FOUND')
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 194, in handle_req
    destination = self.ruler.get_destination(path, rules, True)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/pathfinder.py", line 56, in get_destination
    raise FileNotFoundError(url, rules)
FileNotFoundError: [Errno /serve] {'/': 'tmp/index.html', '/favicon.ico': 'tmp/pictures/favicon.ico', '/index.html': 'tmp/index.html', '/2.html': 'tmp/pages/2.html', '/1.2.3.txt': 'tmp/1.2.3.txt', '/page-load-errors[extras].css': {'path': 'pages/page-load-errors[extras].css', 'mime': 'text/css'}, '/[name].html': 'tmp/pages/[name].html', '/[name].css': 'tmp/pages/css/[name].css', '/[name].[ext]': 'tmp/pictures/[name].[ext]', '/png/[name].png': 'tmp/pictures/[name].png', '/pictures/[ext]/1': 'tmp/pictures/1.[ext]', '/[day]-[n]/[month]/[year]': 'tmp/dates/[year]/[month]/[day]/[n].png', '/[DD]/[MM]/[YY]': 'tmp/dates/[DD].[MM].[YY].png', '/mime/': {'path': 'tmp/pictures/1.png', 'mime': 'text/txt'}, '/big': {'path': 'tmp/pictures/chroma.jpg', 'mime': 'image/jpg'}, '/[file].[ext]': 'tmp/[file].[ext]'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 111, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 196, in handle_req
    raise Errors.NOT_FOUND
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 111, in serve_client
    res = self.handle_req(req)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 196, in handle_req
    raise Errors.NOT_FOUND
errors.Error: (404, 'Not found', '', 'PAGE_NOT_FOUND')
INFO:root:1800004B sent to ('127.0.0.1', 53721)
INFO:root:1089B sent to ('127.0.0.1', 53713)
INFO:root:Files sent to ('127.0.0.1', 53713)
INFO:root:1571928B sent to ('127.0.0.1', 53721)
INFO:root:1473156B sent to ('127.0.0.1', 53721)
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Threaded client serving started ('127.0.0.1', 53713) in thread 4669779392
INFO:root:Request parsed from ('127.0.0.1', 53713) method: GET
target: /page-load-errors.css
version: HTTP/1.1
headers: Host: 0.0.0.0:8000
Connection: keep-alive
Accept: text/css,*/*;q=0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Referer: http://0.0.0.0:8000/serve
Accept-Encoding: gzip, deflate


file: <_io.BytesIO object at 0x11014ba70>
user: ('127.0.0.1', 53713)
url: ParseResult(scheme='', netloc='', path='/page-load-errors.css', params='', query='', fragment='')
path: /page-load-errors.css
query: {}
INFO:root:1800420B sent to ('127.0.0.1', 53721)
INFO:root:Threaded client serving started ('127.0.0.1', 53718) in thread 4669779392
INFO:root:Request parsing by connection started
INFO:root:Path processing /page-load-errors.css
INFO:root:Parsing request by file started
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/pages/page-load-errors.css
INFO:root:1637048B sent to ('127.0.0.1', 53721)
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53718) method: GET
target: /page-load-errors-extras.css
version: HTTP/1.1
headers: Host: 0.0.0.0:8000
Connection: keep-alive
Accept: text/css,*/*;q=0.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Accept-Language: en-us
Referer: http://0.0.0.0:8000/serve
Accept-Encoding: gzip, deflate


file: <_io.BytesIO object at 0x110154cb0>
user: ('127.0.0.1', 53718)
url: ParseResult(scheme='', netloc='', path='/page-load-errors-extras.css', params='', query='', fragment='')
path: /page-load-errors-extras.css
query: {}
INFO:root:1637464B sent to ('127.0.0.1', 53721)
INFO:root:621708B sent to ('127.0.0.1', 53721)
INFO:root:Path processing /page-load-errors-extras.css
INFO:root:1358780B sent to ('127.0.0.1', 53721)
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/css'), ('Content-Disposition', 'inline; filename=page-load-errors.css'), ('Content-Length', 1129)]
body: b'/*\n    This file has a UTF-8 BOM in it so it can be included from a UTF-16 page\n    without specifying an explicit character set. When editing it, please be\n    sure to preserve the BOM (first three bytes of the file, EF BB BF).\n */\n\nbody {\n    background: rgb(246, 246, 246);\n    cursor: default;\n    display: -webkit-box;\n    text-align: center;\n    -webkit-box-align: center;\n    -webkit-box-pack: center;\n    -webkit-user-select: none;\n}\n\na {\n    color: rgb(21, 126, 251);\n   
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/pages/page-load-errors-extras.css
INFO:root:1254B sent to ('127.0.0.1', 53713)
INFO:root:1439608B sent to ('127.0.0.1', 53721)
INFO:root:Files sent to ('127.0.0.1', 53713)
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/css'), ('Content-Disposition', 'inline; filename=page-load-errors-extras.css'), ('Content-Length', 407)]
body: b'/*\n    This file has a UTF-8 BOM in it so it can be included from a UTF-16 page\n    without specifying an explicit character set. When editing it, please be\n    sure to preserve the BOM (first three bytes of the file, EF BB BF).\n*/\n\n@media (prefers-dark-interface) {\n    body {\n        background: rgb(30, 30, 30);\n    }\n\n    .error-message, .suggestion-prompt {\n        color: rgb(110, 110, 110);\n    }\n}\n\n'
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/css'), ('Content-Disposition', 'inline; filename=page-load-errors.css'), ('Content-Length', 1129)]
body: b'/*\n    This file has a UTF-8 BOM in it so it can be included from a UTF-16 page\n    without specifying an explicit character set. When editing it, please be\n    sure to preserve the BOM (first three bytes of the file, EF BB BF).\n */\n\nbody {\n    background: rgb(246, 246, 246);\n    cursor: default;\n    display: -webkit-box;\n    text-align: center;\n    -webkit-box-align: center;\n    -webkit-box-pack: center;\n    -webkit-user-select: none;\n}\n\na {\n    color: rgb(21, 126, 251);\n   
INFO:root:1604228B sent to ('127.0.0.1', 53721)
INFO:root:538B sent to ('127.0.0.1', 53718)
INFO:root:Files sent to ('127.0.0.1', 53718)
INFO:root:1440024B sent to ('127.0.0.1', 53721)
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/css'), ('Content-Disposition', 'inline; filename=page-load-errors-extras.css'), ('Content-Length', 407)]
body: b'/*\n    This file has a UTF-8 BOM in it so it can be included from a UTF-16 page\n    without specifying an explicit character set. When editing it, please be\n    sure to preserve the BOM (first three bytes of the file, EF BB BF).\n*/\n\n@media (prefers-dark-interface) {\n    body {\n        background: rgb(30, 30, 30);\n    }\n\n    .error-message, .suggestion-prompt {\n        color: rgb(110, 110, 110);\n    }\n}\n\n'
INFO:root:1504936B sent to ('127.0.0.1', 53721)
INFO:root:1504728B sent to ('127.0.0.1', 53721)
INFO:root:1604228B sent to ('127.0.0.1', 53721)
INFO:root:1570680B sent to ('127.0.0.1', 53721)
INFO:root:1604228B sent to ('127.0.0.1', 53721)
INFO:root:1506392B sent to ('127.0.0.1', 53721)
INFO:root:1751268B sent to ('127.0.0.1', 53721)
INFO:root:1455992B sent to ('127.0.0.1', 53721)
INFO:root:1586648B sent to ('127.0.0.1', 53721)
INFO:root:1521320B sent to ('127.0.0.1', 53721)
INFO:root:1857348B sent to ('127.0.0.1', 53721)
INFO:root:1522776B sent to ('127.0.0.1', 53721)
INFO:root:1826910B sent to ('127.0.0.1', 53721)
INFO:root:Files sent to ('127.0.0.1', 53721)
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/plain'), ('Content-Disposition', 'inline; filename=server.log'), ('Content-Length', 65220561)]
body: b'INFO:root:server is UP on 0.0.0.0:8000\nINFO:root:Connected (\'127.0.0.1\', 50810)\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasdasdasdasdasd\nINFO:root:FILL THIS MKSADMKASDKASDKasdasdasdasda
ERROR:root:No data received
INFO:root:Threaded client serving started ('127.0.0.1', 53713) in thread 4669779392
ERROR:root:Client handling failed (123145425727488) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
ERROR:root:No data received
INFO:root:Threaded client serving started ('127.0.0.1', 53713) in thread 4669779392
INFO:root:107B sent to ('127.0.0.1', 53713)
ERROR:root:Client handling failed (123145430982656) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
ERROR:root:No data received
INFO:root:Threaded client serving started ('127.0.0.1', 53718) in thread 4669779392
INFO:root:Files sent to ('127.0.0.1', 53713)
ERROR:root:Client handling failed (123145436237824) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
ERROR:root:No data received
INFO:root:Threaded client serving started ('127.0.0.1', 53720) in thread 4669779392
INFO:root:107B sent to ('127.0.0.1', 53718)
ERROR:root:Client handling failed (123145430982656) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Files sent to ('127.0.0.1', 53718)
INFO:root:Socket in thread 4669779392 was disconnected [Errno 22] Invalid argument
ERROR:root:No data received
INFO:root:107B sent to ('127.0.0.1', 53720)
INFO:root:Socket Disconnected in thread 4669779392
ERROR:root:Client handling failed (123145425727488) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Files sent to ('127.0.0.1', 53720)
ERROR:root:No data received
INFO:root:Socket in thread 4669779392 was disconnected [Errno 22] Invalid argument
ERROR:root:Connection with client broken
ERROR:root:Client handling failed (123145436237824) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Socket Disconnected in thread 4669779392
INFO:root:Socket in thread 4669779392 was disconnected [Errno 22] Invalid argument
ERROR:root:No data received
INFO:root:Socket Disconnected in thread 4669779392
ERROR:root:Client handling failed (123145425727488) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
ERROR:root:Connection with client broken
INFO:root:Threaded client serving started ('127.0.0.1', 53721) in thread 4669779392
ERROR:root:No data received
ERROR:root:No data received
INFO:root:Threaded client serving started ('127.0.0.1', 53721) in thread 4669779392
ERROR:root:Client handling failed (123145425727488) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
ERROR:root:Client handling failed (123145430982656) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
ERROR:root:No data received
INFO:root:Threaded client serving started ('127.0.0.1', 53721) in thread 4669779392
INFO:root:107B sent to ('127.0.0.1', 53721)
ERROR:root:Client handling failed (123145436237824) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Socket in thread 4669779392 was disconnected [Errno 22] Invalid argument
ERROR:root:No data received
INFO:root:Files sent to ('127.0.0.1', 53721)
INFO:root:Socket Disconnected in thread 4669779392
ERROR:root:Client handling failed (123145430982656) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 109, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 121, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 144, in receive_from_client
    raise Exception('No data received')
Exception: No data received
ERROR:root:Connection with client broken
INFO:root:server is DOWN with no exceptions
INFO:root:Path processing /pictures/png/1
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/1.png
INFO:root:Path processing /no.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.css') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/no.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/no.css
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/no.css
INFO:root:Path processing /mime/
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/1.png
INFO:root:Path processing /index.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Path processing /1.2.3.txt
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/1.2.3.txt
INFO:root:Path processing /foo.bar
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/foo.bar
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/foo.bar
INFO:root:Path processing /any.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/any.html
INFO:root:Path processing /2.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/2.html
INFO:root:Path processing /123.css
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/123.css
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Path processing /new page.html
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.html') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/new page.html
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/new page.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/new page.html
INFO:root:Parsing request by file started
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Parsing request by file started
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:server is UP on 0.0.0.0:8000
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Connected ('127.0.0.1', 53776)
INFO:root:Request parsing by connection started
INFO:root:Threaded client serving started ('127.0.0.1', 53776) in thread 4578889152
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53776) method: GET
target: /
version: HTTP/1.1
headers: Host: 0.0.0.0
Accept: */*


file: <_io.BytesIO object at 0x10c48ee90>
user: ('127.0.0.1', 53776)
url: ParseResult(scheme='', netloc='', path='/', params='', query='', fragment='')
path: /
query: {}
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/html'), ('Content-Disposition', 'inline; filename=index.html'), ('Content-Length', 156)]
body: b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>index.html</title>\n</head>\n<body>\n    <h1>Python Rule it!</h1>\n</body>\n</html>'
INFO:root:271B sent to ('127.0.0.1', 53776)
INFO:root:Files sent to ('127.0.0.1', 53776)
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/html'), ('Content-Disposition', 'inline; filename=index.html'), ('Content-Length', 156)]
body: b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>index.html</title>\n</head>\n<body>\n    <h1>Python Rule it!</h1>\n</body>\n</html>'
ERROR:root:No data received
INFO:root:Threaded client serving started ('127.0.0.1', 53776) in thread 4578889152
ERROR:root:Client handling failed (123145385672704) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 108, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 120, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 143, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Threaded client serving started ('127.0.0.1', 53776) in thread 4578889152
ERROR:root:No data received
INFO:root:107B sent to ('127.0.0.1', 53776)
ERROR:root:No data received
INFO:root:Socket in thread 4578889152 was disconnected [Errno 22] Invalid argument
ERROR:root:Client handling failed (123145390927872) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 108, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 120, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 143, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Files sent to ('127.0.0.1', 53776)
ERROR:root:Client handling failed (123145396183040) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 108, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 120, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 143, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Socket Disconnected in thread 4578889152
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:Path processing /pictures/png/1
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/1.png
INFO:root:Path processing /no.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.css') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/no.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/no.css
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/no.css
INFO:root:Path processing /mime/
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/1.png
INFO:root:Path processing /index.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Path processing /1.2.3.txt
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/1.2.3.txt
INFO:root:Path processing /foo.bar
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/foo.bar
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/foo.bar
INFO:root:Path processing /any.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/any.html
INFO:root:Path processing /2.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/2.html
INFO:root:Path processing /123.css
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/123.css
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Path processing /new page.html
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.html') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/new page.html
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/new page.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/new page.html
INFO:root:Parsing request by file started
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Parsing request by file started
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:server is UP on 0.0.0.0:8000
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Connected ('127.0.0.1', 53781)
INFO:root:Threaded client serving started ('127.0.0.1', 53781) in thread 4465831360
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53781) method: GET
target: /
version: HTTP/1.1
headers: Host: 0.0.0.0
Accept: */*


file: <_io.BytesIO object at 0x10ad87d10>
user: ('127.0.0.1', 53781)
url: ParseResult(scheme='', netloc='', path='/', params='', query='', fragment='')
path: /
query: {}
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/html'), ('Content-Disposition', 'inline; filename=index.html'), ('Content-Length', 156)]
body: b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>index.html</title>\n</head>\n<body>\n    <h1>Python Rule it!</h1>\n</body>\n</html>'
INFO:root:271B sent to ('127.0.0.1', 53781)
INFO:root:Files sent to ('127.0.0.1', 53781)
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/html'), ('Content-Disposition', 'inline; filename=index.html'), ('Content-Length', 156)]
body: b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>index.html</title>\n</head>\n<body>\n    <h1>Python Rule it!</h1>\n</body>\n</html>'
INFO:root:Threaded client serving started ('127.0.0.1', 53781) in thread 4465831360
ERROR:root:No data received
ERROR:root:No data received
INFO:root:Threaded client serving started ('127.0.0.1', 53781) in thread 4465831360
ERROR:root:Client handling failed (123145574301696) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 108, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 120, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 143, in receive_from_client
    raise Exception('No data received')
Exception: No data received
ERROR:root:Client handling failed (123145579556864) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 108, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 120, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 143, in receive_from_client
    raise Exception('No data received')
Exception: No data received
ERROR:root:No data received
INFO:root:Threaded client serving started ('127.0.0.1', 53781) in thread 4465831360
INFO:root:107B sent to ('127.0.0.1', 53781)
ERROR:root:Client handling failed (123145584812032) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 108, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 120, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 143, in receive_from_client
    raise Exception('No data received')
Exception: No data received
ERROR:root:No data received
INFO:root:Socket in thread 4465831360 was disconnected [Errno 22] Invalid argument
INFO:root:Files sent to ('127.0.0.1', 53781)
ERROR:root:Client handling failed (123145579556864) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 108, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 120, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 143, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Socket Disconnected in thread 4465831360
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:Path processing /pictures/png/1
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/1.png
INFO:root:Path processing /no.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.css') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/no.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/no.css
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/no.css
INFO:root:Path processing /mime/
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/1.png
INFO:root:Path processing /index.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Path processing /1.2.3.txt
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/1.2.3.txt
INFO:root:Path processing /foo.bar
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/foo.bar
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/foo.bar
INFO:root:Path processing /any.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/any.html
INFO:root:Path processing /2.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/2.html
INFO:root:Path processing /123.css
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/123.css
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Path processing /new page.html
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.html') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/new page.html
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/new page.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/new page.html
INFO:root:Parsing request by file started
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Parsing request by file started
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:server is UP on 0.0.0.0:8000
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Connected ('127.0.0.1', 53791)
INFO:root:Threaded client serving started ('127.0.0.1', 53791) in thread 4504821184
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53791) method: GET
target: /
version: HTTP/1.1
headers: Host: 0.0.0.0
Accept: */*


file: <_io.BytesIO object at 0x101b95cb0>
user: ('127.0.0.1', 53791)
url: ParseResult(scheme='', netloc='', path='/', params='', query='', fragment='')
path: /
query: {}
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/html'), ('Content-Disposition', 'inline; filename=index.html'), ('Content-Length', 156)]
body: b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>index.html</title>\n</head>\n<body>\n    <h1>Python Rule it!</h1>\n</body>\n</html>'
INFO:root:271B sent to ('127.0.0.1', 53791)
INFO:root:Files sent to ('127.0.0.1', 53791)
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/html'), ('Content-Disposition', 'inline; filename=index.html'), ('Content-Length', 156)]
body: b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>index.html</title>\n</head>\n<body>\n    <h1>Python Rule it!</h1>\n</body>\n</html>'
ERROR:root:No data received
ERROR:root:Client handling failed (123145478295552) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 108, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 120, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 143, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Threaded client serving started ('127.0.0.1', 53791) in thread 4504821184
INFO:root:107B sent to ('127.0.0.1', 53791)
INFO:root:Files sent to ('127.0.0.1', 53791)
INFO:root:Socket in thread 4504821184 was disconnected [Errno 22] Invalid argument
INFO:root:Socket Disconnected in thread 4504821184
ERROR:root:No data received
ERROR:root:Client handling failed (123145478295552) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 108, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 120, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 143, in receive_from_client
    raise Exception('No data received')
Exception: No data received
ERROR:root:Connection with client broken
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:Path processing /pictures/png/1
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/1.png
INFO:root:Path processing /no.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.css') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/no.css
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/no.css
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/no.css
INFO:root:Path processing /mime/
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/1.png
INFO:root:Path processing /index.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Path processing /1.2.3.txt
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/1.2.3.txt
INFO:root:Path processing /foo.bar
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/foo.bar
ERROR:root:Path matched by rule re.compile('/(?P<file>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/foo.bar
INFO:root:Path processing /any.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/any.html
INFO:root:Path processing /2.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/2.html
INFO:root:Path processing /123.css
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/css/123.css
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Path processing /new page.html
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.html') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pages/new page.html
ERROR:root:Path matched by rule re.compile('/(?P<name>.*)\\.(?P<ext>.*)') but file not found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/pictures/new page.html
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/new page.html
INFO:root:Parsing request by file started
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Parsing request by file started
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:server is UP on 0.0.0.0:8000
ERROR:root:server is DOWN because of exception None None None
NoneType: None
INFO:root:server is UP on 0.0.0.0:8000
INFO:root:Connected ('127.0.0.1', 53796)
INFO:root:Threaded client serving started ('127.0.0.1', 53796) in thread 4528790976
INFO:root:Request parsing by connection started
INFO:root:Parsing request by file started
INFO:root:Request parsed
INFO:root:Request parsed from ('127.0.0.1', 53796) method: GET
target: /
version: HTTP/1.1
headers: Host: 0.0.0.0
Accept: */*


file: <_io.BytesIO object at 0x101c98cb0>
user: ('127.0.0.1', 53796)
url: ParseResult(scheme='', netloc='', path='/', params='', query='', fragment='')
path: /
query: {}
INFO:root:Path processing /
INFO:root:Path found /Users/irusland/Desktop/UrFU/python/httpserver/tmp/index.html
INFO:root:Response prepared 
status: 200
reason: OK
headers: [('Content-Type', 'text/html'), ('Content-Disposition', 'inline; filename=index.html'), ('Content-Length', 156)]
body: b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>index.html</title>\n</head>\n<body>\n    <h1>Python Rule it!</h1>\n</body>\n</html>'
INFO:root:271B sent to ('127.0.0.1', 53796)
INFO:root:Files sent to ('127.0.0.1', 53796)
INFO:root:Response sent 
status: 200
reason: OK
headers: [('Content-Type', 'text/html'), ('Content-Disposition', 'inline; filename=index.html'), ('Content-Length', 156)]
body: b'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>index.html</title>\n</head>\n<body>\n    <h1>Python Rule it!</h1>\n</body>\n</html>'
INFO:root:Threaded client serving started ('127.0.0.1', 53796) in thread 4528790976
ERROR:root:No data received
ERROR:root:Client handling failed (123145321963520) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 108, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 120, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 143, in receive_from_client
    raise Exception('No data received')
Exception: No data received
ERROR:root:No data received
INFO:root:Threaded client serving started ('127.0.0.1', 53796) in thread 4528790976
INFO:root:107B sent to ('127.0.0.1', 53796)
INFO:root:Files sent to ('127.0.0.1', 53796)
ERROR:root:No data received
INFO:root:Socket in thread 4528790976 was disconnected [Errno 22] Invalid argument
ERROR:root:Client handling failed (123145327218688) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 108, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 120, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 143, in receive_from_client
    raise Exception('No data received')
Exception: No data received
ERROR:root:Client handling failed (123145332473856) No data received
Traceback (most recent call last):
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 108, in serve_client
    req = self.parse_req_connection(connection)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 120, in parse_req_connection
    req_bytes = self.receive_from_client(client)
  File "/Users/irusland/Desktop/UrFU/python/httpserver/httpserver.py", line 143, in receive_from_client
    raise Exception('No data received')
Exception: No data received
INFO:root:Socket Disconnected in thread 4528790976
ERROR:root:server is DOWN because of exception None None None
NoneType: None
